Joimer/Pokemon-Showdown

- config/formats.js
- data/scripts.js
Hastily typed out at work, and completely untested. It should highlight all the concepts we mentioned for the format, though.
> Implement basic version of Mulan Seasonal

- mods/skillmons/statuses.js
For now, half of status is not implemented, but it's better than nothing.
> Implement stall mechanics

- config/formats.js
Zarel's signature move is a two-hit attack. The first hit is a Special
Psychic attack, and then Zarel transforms into Pirouette forme and the
second hit is a Physical Fighting attack.
> Seasonal: Implement Zarel's Signature Move properly

- data/scripts.js
Changes required by L51 in the Piratepad
> Update Level 51 set

- config/formats.js
- data/scripts.js
- Improve onResidual
- Update Bri and V4's sig
- Fix qtrx and Eevee General's sig
- Move imanalt
- Update Bri and qtrx sets
> Ninja fixes

- config/formats.js
After a lengthy chat with shaymin, we decided that her sig move would be slightly nerfed and that she would change formes like Aegislash by using status or attacking moves.
Fix Tempoanon name as requested.
Fix Hippopotas switch out message.
Fix Redew Toxic message.
Update qtrx innate ability.
> Update shaymin set

- config/formats.js
The current checks against Illusion are not functioning as intended. Slayer95 will become very OP once he turns into innovo.
> Nerf Illusion in SSB

- config/formats.js
- data/scripts.js
Jac, TTT, Frizy, Diatom and Kenny's sets are still missing stuff.
btw @Joimer or whoever changed it wasn't the level scale 99, 98, 96, 95, 93? I thought that made more sense and better reflected the significance of our ranks.
scalar's EVs have been updated since it was very bad and didn't make sense with his item. The pad simply said '252 HP' so I went with max+ speed.
> Add all remaining completed sets

- config/formats.js
- data/scripts.js
Changelist:
- Buff Okuu, change custom
- Nerf Reverb, DTC, Lawrence III
- Enable Choice items to lock on custom moves
- Buff Scalar
- Fix mega hack
- Other minor fixes
Note: We might want to persuade V4 @DanUgore to give up Dragon Ascent in his set since that potentially causes the mega evolution box to appear (and crash the battle when checked) due to our hack. Of course if you guys can prevent that it would be even better!
> Staff Bros: Balance Update batch 1

- config/formats.js
- data/scripts.js
Changelist:
- Mod rekeri
- Change Protect base moves to Detect
- Update WaterBomb sig
- Nerf Audiosurfer sig
> Staff Bros: Balance Update batch 2

- config/formats.js
- data/scripts.js
Changelist:
- Add Diatom
- Properly implement Slayer95 sig
- Update Lawrence III, qtrx, mikel sig
- Fix Bean sig
- Promote Eevee General
- Add some hidden fun for chaos
> Staff Bros: Fixes, and Thanks Diatom!

- config/formats.js
- data/scripts.js
> First version of Seasonals

- config/formats.js
Fixing minor mistake I made earlier.
For future reference, would you rather I do several commits of different things in one pullreq or multiple pullreqs for things not quire related like I have been doing?
> SSBM: Fix Bummer's Entry and Faint Messages

- mods/seasonal/moves.js
- mods/seasonal/scripts.js
Simplified variant set syntax.
> Add boTTT and its move

- config/formats.js
- mods/seasonal/moves.js
- mods/seasonal/scripts.js
> SSBM: Add f(x)

- config/formats.js
- mods/seasonal/moves.js
- mods/seasonal/scripts.js
> SSBM: (dog)

- config/formats.js
- mods/seasonal/moves.js
Retreat: seemed too powerful since it could OHKO most of the meta. QQ suggested lowering BP to 60. Not sure if this is enough of a nerf, however.
Wonder Bark: some of the moves it gives are now better. Also removed some unnecessary LoC.
Sacred Spear Explosion: While Trickster is extremely good from a utility standpoint, this move just did not seem up to part with some of the other mons. Trickster asked the bp be raised to 100.
> SSBM: minor balancing to moves

- mods/seasonal/moves.js
Eevee General should still be able to switch out and add debuffs even if
the move fails to add psn or taunt
Standing Full's confusion shouldn't apply to Pokemon that have Shield Dust.
> SSBM: sig move bug fixes

- config/formats.js
- mods/seasonal/moves.js
- mods/seasonal/statuses.js
- Fix typo in Jetpack's sig
- Fix logic in Death on Wings sig
> Fix sig moves

- config/formats.js
- mods/seasonal/README.md
- mods/seasonal/moves.js
- mods/seasonal/scripts.js
- mods/seasonal/statuses.js
- Changed effect of E4 Flint and Flying Kebab sigs as requested
- <s>Revert nv innate,</s> changed nv sig effect for better synergy
- Stop Wonder Guard from cursing bludz
- Fix various typos
- Update documentation
- Other balance changes
> Balance changes and patch for SSBM

- config/formats.js
- mods/seasonal/README.md
- mods/seasonal/moves.js
- mods/seasonal/scripts.js
- mods/seasonal/statuses.js
- Various balance fixes
- Update documentation
> Update and fix SSBM
